import { LevelDef } from "./LevelData";

export const LEVELS: LevelDef[] = [
    {
        id: "level_1",
        name: "Wooden Warmup",
        skybox: "tropical",
        launcherPosition: { x: -12, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.4, z: 0 },
        maxShots: 3,
        starThresholds: [150, 300, 500],
        timeBonusThreshold: 30,
        targets: [
            { position: { x: 10.2, y: 3.05, z: 0 }, size: 0.8, health: 1, scoreValue: 120 },
            { position: { x: 13.8, y: 0.5, z: 0.8 }, size: 0.8, health: 1, scoreValue: 120 },
        ],
        obstacles: [
            {
                position: { x: 9, y: 0, z: 0 },
                size: { x: 0.6, y: 2.4, z: 1.2 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
            {
                position: { x: 11.4, y: 0, z: 0 },
                size: { x: 0.6, y: 2.4, z: 1.2 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
            {
                position: { x: 10.2, y: 2.6, z: 0 },
                size: { x: 2.7, y: 0.4, z: 1.2 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
            {
                position: { x: 13.2, y: 0, z: 0.8 },
                size: { x: 0.7, y: 1.6, z: 0.9 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_2",
        name: "Twin Tower Test",
        skybox: "tropical",
        launcherPosition: { x: -14, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.46, z: 0 },
        maxShots: 4,
        starThresholds: [250, 500, 850],
        timeBonusThreshold: 40,
        targets: [
            { position: { x: 10.35, y: 0.5, z: 0 }, size: 0.8, health: 1, scoreValue: 120 },
            { position: { x: 12.3, y: 1.85, z: -0.5 }, size: 0.8, health: 1, scoreValue: 150 },
            { position: { x: 14.15, y: 4.05, z: -1.2 }, size: 0.8, health: 2, scoreValue: 220 },
        ],
        obstacles: [
            {
                position: { x: 9.5, y: 0, z: 0 },
                size: { x: 0.5, y: 2.8, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 11.2, y: 0, z: 0 },
                size: { x: 0.5, y: 2.8, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 10.35, y: 3.0, z: 0 },
                size: { x: 2.3, y: 0.4, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 12.3, y: 1.2, z: -0.5 },
                size: { x: 3.6, y: 0.5, z: 1.5 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 13.3, y: 0, z: -1.2 },
                size: { x: 0.5, y: 3.4, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 15.0, y: 0, z: -1.2 },
                size: { x: 0.5, y: 3.4, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 14.15, y: 3.6, z: -1.2 },
                size: { x: 2.3, y: 0.4, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_3",
        name: "Core Charge",
        skybox: "night",
        launcherPosition: { x: -14, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.5, z: 0 },
        maxShots: 5,
        starThresholds: [350, 700, 1100],
        timeBonusThreshold: 55,
        targets: [
            { position: { x: 12.5, y: 0.5, z: 0 }, size: 0.8, health: 1, scoreValue: 120 },
            { position: { x: 12.5, y: 4.7, z: 0 }, size: 0.8, health: 1, scoreValue: 170 },
            { position: { x: 12.5, y: 6.55, z: 0 }, size: 0.8, health: 2, scoreValue: 260 },
            { position: { x: 16.0, y: 3.45, z: -2.0 }, size: 0.8, health: 1, scoreValue: 180 },
        ],
        powerups: [
            { position: { x: 10.0, y: 5.0, z: 0.2 }, size: 0.75, type: "titanCore" },
        ],
        obstacles: [
            {
                position: { x: 11.2, y: 0, z: 0 },
                size: { x: 0.6, y: 4.0, z: 1.6 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 13.8, y: 0, z: 0 },
                size: { x: 0.6, y: 4.0, z: 1.6 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 12.5, y: 4.2, z: 0 },
                size: { x: 3.2, y: 0.45, z: 1.6 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 11.7, y: 4.9, z: 0 },
                size: { x: 0.5, y: 2.0, z: 1.2 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 13.3, y: 4.9, z: 0 },
                size: { x: 0.5, y: 2.0, z: 1.2 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 12.5, y: 6.0, z: 0 },
                size: { x: 2.6, y: 0.4, z: 1.2 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 16.0, y: 0, z: -2.0 },
                size: { x: 0.7, y: 2.8, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 16.0, y: 3.05, z: -2.0 },
                size: { x: 1.8, y: 0.35, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_4",
        name: "Powder Kegs",
        skybox: "night",
        launcherPosition: { x: -15, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.5, z: 0 },
        maxShots: 5,
        starThresholds: [500, 900, 1400],
        timeBonusThreshold: 60,
        targets: [
            { position: { x: 19.0, y: 0.5, z: 0 }, size: 0.8, health: 1, scoreValue: 120 },
            { position: { x: 19.0, y: 2.55, z: 0 }, size: 0.8, health: 1, scoreValue: 180 },
            { position: { x: 19.0, y: 4.75, z: 0 }, size: 0.8, health: 2, scoreValue: 260 },
            { position: { x: 15.7, y: 3.9, z: -2.2 }, size: 0.8, health: 1, scoreValue: 180 },
            { position: { x: 18.9, y: 2.55, z: 0 }, size: 0.95, health: 1, scoreValue: 80, type: "barrel" },
            { position: { x: 15.7, y: 0.65, z: -2.2 }, size: 0.95, health: 1, scoreValue: 80, type: "barrel" },
        ],
        obstacles: [
            {
                position: { x: 18.0, y: 0, z: 0 },
                size: { x: 0.6, y: 4.0, z: 2.0 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 20.0, y: 0, z: 0 },
                size: { x: 0.6, y: 4.0, z: 2.0 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 19.0, y: 2.0, z: 0 },
                size: { x: 2.2, y: 0.35, z: 1.5 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 19.0, y: 4.2, z: 0 },
                size: { x: 3.0, y: 0.4, z: 2.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 14.5, y: 0, z: -2.2 },
                size: { x: 0.6, y: 3.2, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 16.9, y: 0, z: -2.2 },
                size: { x: 0.6, y: 3.2, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 15.7, y: 3.4, z: -2.2 },
                size: { x: 2.6, y: 0.4, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_5",
        name: "Castle Cascade",
        skybox: "night",
        launcherPosition: { x: -16, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.52, z: 0 },
        maxShots: 6,
        starThresholds: [700, 1200, 1800],
        timeBonusThreshold: 70,
        targets: [
            { position: { x: 12.5, y: 3.65, z: 2.0 }, size: 0.8, health: 1, scoreValue: 180 },
            { position: { x: 18.0, y: 0.5, z: 0 }, size: 0.8, health: 1, scoreValue: 140 },
            { position: { x: 18.0, y: 2.75, z: 0 }, size: 0.8, health: 2, scoreValue: 220 },
            { position: { x: 20.8, y: 2.3, z: -1.0 }, size: 0.8, health: 1, scoreValue: 180 },
            { position: { x: 23.0, y: 4.25, z: -2.0 }, size: 0.8, health: 2, scoreValue: 280 },
            { position: { x: 17.9, y: 2.75, z: 0 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
            { position: { x: 22.9, y: 0.65, z: -2.0 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
            { position: { x: 12.5, y: 0.65, z: 2.0 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
        ],
        obstacles: [
            {
                position: { x: 11.8, y: 0, z: 2.0 },
                size: { x: 0.5, y: 3.0, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 13.2, y: 0, z: 2.0 },
                size: { x: 0.5, y: 3.0, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 12.5, y: 3.2, z: 2.0 },
                size: { x: 2.2, y: 0.4, z: 1.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 17.0, y: 0, z: 0 },
                size: { x: 0.6, y: 4.2, z: 2.0 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 19.0, y: 0, z: 0 },
                size: { x: 0.6, y: 4.2, z: 2.0 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 18.0, y: 2.2, z: 0 },
                size: { x: 3.4, y: 0.45, z: 2.0 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 18.0, y: 4.4, z: 0 },
                size: { x: 3.0, y: 0.4, z: 2.0 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 22.2, y: 0, z: -2.0 },
                size: { x: 0.5, y: 3.6, z: 1.2 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 23.8, y: 0, z: -2.0 },
                size: { x: 0.5, y: 3.6, z: 1.2 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 23.0, y: 3.8, z: -2.0 },
                size: { x: 2.4, y: 0.35, z: 1.2 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 20.8, y: 1.8, z: -1.0 },
                size: { x: 5.2, y: 0.35, z: 1.2 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_6",
        name: "Barrel Bridge",
        skybox: "tropical",
        launcherPosition: { x: -17, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.5, z: 0 },
        maxShots: 6,
        starThresholds: [900, 1500, 2200],
        timeBonusThreshold: 75,
        targets: [
            { position: { x: 16.0, y: 0.55, z: 0 }, size: 0.8, health: 1, scoreValue: 140 },
            { position: { x: 18.4, y: 2.8, z: -0.6 }, size: 0.8, health: 1, scoreValue: 180 },
            { position: { x: 21.0, y: 5.15, z: -1.2 }, size: 0.8, health: 2, scoreValue: 260 },
            { position: { x: 24.0, y: 2.85, z: -2.2 }, size: 0.8, health: 2, scoreValue: 240 },
            { position: { x: 18.4, y: 0.7, z: -0.6 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
            { position: { x: 21.0, y: 2.95, z: -1.2 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
            { position: { x: 24.0, y: 0.7, z: -2.2 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
        ],
        powerups: [
            { position: { x: 14.4, y: 3.9, z: 0.1 }, size: 0.75, type: "titanCore" },
        ],
        obstacles: [
            { position: { x: 15.2, y: 0, z: 0 }, size: { x: 0.6, y: 3.0, z: 1.2 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 16.8, y: 0, z: 0 }, size: { x: 0.6, y: 3.0, z: 1.2 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 16.0, y: 3.0, z: 0 }, size: { x: 2.4, y: 0.35, z: 1.2 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 17.6, y: 0, z: -0.6 }, size: { x: 0.65, y: 3.6, z: 1.2 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 19.2, y: 0, z: -0.6 }, size: { x: 0.65, y: 3.6, z: 1.2 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 18.4, y: 3.6, z: -0.6 }, size: { x: 2.6, y: 0.4, z: 1.2 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 20.2, y: 0, z: -1.2 }, size: { x: 0.65, y: 4.2, z: 1.3 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 21.8, y: 0, z: -1.2 }, size: { x: 0.65, y: 4.2, z: 1.3 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 21.0, y: 4.6, z: -1.2 }, size: { x: 2.7, y: 0.4, z: 1.3 }, destructible: true, health: 3, materialType: "wood" },
            { position: { x: 23.2, y: 0, z: -2.2 }, size: { x: 0.6, y: 3.2, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 24.8, y: 0, z: -2.2 }, size: { x: 0.6, y: 3.2, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 24.0, y: 3.2, z: -2.2 }, size: { x: 2.3, y: 0.35, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
        ],
    },
    {
        id: "level_7",
        name: "Core Relay",
        skybox: "night",
        launcherPosition: { x: -18, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.52, z: 0 },
        maxShots: 7,
        starThresholds: [1200, 1900, 2800],
        timeBonusThreshold: 85,
        targets: [
            { position: { x: 14.6, y: 0.55, z: 1.6 }, size: 0.8, health: 1, scoreValue: 160 },
            { position: { x: 18.8, y: 3.0, z: 0.2 }, size: 0.8, health: 2, scoreValue: 220 },
            { position: { x: 22.7, y: 0.55, z: -1.4 }, size: 0.8, health: 1, scoreValue: 170 },
            { position: { x: 26.2, y: 4.9, z: -2.3 }, size: 0.8, health: 2, scoreValue: 280 },
            { position: { x: 18.8, y: 0.7, z: 0.2 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
            { position: { x: 22.7, y: 2.95, z: -1.4 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
            { position: { x: 26.2, y: 1.0, z: -2.3 }, size: 0.95, health: 1, scoreValue: 90, type: "barrel" },
        ],
        powerups: [
            { position: { x: 16.7, y: 4.4, z: 0.5 }, size: 0.75, type: "titanCore" },
            { position: { x: 24.1, y: 4.6, z: -1.8 }, size: 0.75, type: "titanCore" },
        ],
        obstacles: [
            { position: { x: 13.8, y: 0, z: 1.6 }, size: { x: 0.55, y: 3.1, z: 1.0 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 15.4, y: 0, z: 1.6 }, size: { x: 0.55, y: 3.1, z: 1.0 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 14.6, y: 3.05, z: 1.6 }, size: { x: 2.2, y: 0.35, z: 1.0 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 18.0, y: 0, z: 0.2 }, size: { x: 0.65, y: 3.8, z: 1.4 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 19.6, y: 0, z: 0.2 }, size: { x: 0.65, y: 3.8, z: 1.4 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 18.8, y: 3.8, z: 0.2 }, size: { x: 2.5, y: 0.4, z: 1.4 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 22.0, y: 0, z: -1.4 }, size: { x: 0.55, y: 3.2, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 23.4, y: 0, z: -1.4 }, size: { x: 0.55, y: 3.2, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 22.7, y: 3.2, z: -1.4 }, size: { x: 2.2, y: 0.35, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 25.4, y: 0, z: -2.3 }, size: { x: 0.7, y: 4.4, z: 1.4 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 27.0, y: 0, z: -2.3 }, size: { x: 0.7, y: 4.4, z: 1.4 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 26.2, y: 4.5, z: -2.3 }, size: { x: 2.7, y: 0.4, z: 1.4 }, destructible: true, health: 3, materialType: "wood" },
        ],
    },
    {
        id: "level_8",
        name: "Titan Storm",
        skybox: "night",
        launcherPosition: { x: -19, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.54, z: 0 },
        maxShots: 7,
        starThresholds: [1500, 2400, 3400],
        timeBonusThreshold: 95,
        targets: [
            { position: { x: 16.6, y: 0.55, z: 1.9 }, size: 0.8, health: 1, scoreValue: 180 },
            { position: { x: 20.9, y: 3.25, z: 0.6 }, size: 0.8, health: 2, scoreValue: 250 },
            { position: { x: 24.5, y: 3.2, z: -0.9 }, size: 0.8, health: 2, scoreValue: 250 },
            { position: { x: 28.2, y: 5.55, z: -2.5 }, size: 0.8, health: 2, scoreValue: 320 },
            { position: { x: 20.9, y: 0.7, z: 0.6 }, size: 0.95, health: 1, scoreValue: 100, type: "barrel" },
            { position: { x: 24.5, y: 0.7, z: -0.9 }, size: 0.95, health: 1, scoreValue: 100, type: "barrel" },
            { position: { x: 28.2, y: 2.95, z: -2.5 }, size: 0.95, health: 1, scoreValue: 100, type: "barrel" },
        ],
        powerups: [
            { position: { x: 18.3, y: 4.7, z: 1.0 }, size: 0.75, type: "titanCore" },
            { position: { x: 22.9, y: 5.0, z: -0.2 }, size: 0.75, type: "titanCore" },
            { position: { x: 27.1, y: 4.9, z: -1.8 }, size: 0.75, type: "titanCore" },
        ],
        obstacles: [
            { position: { x: 15.8, y: 0, z: 1.9 }, size: { x: 0.6, y: 3.4, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 17.4, y: 0, z: 1.9 }, size: { x: 0.6, y: 3.4, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 16.6, y: 3.4, z: 1.9 }, size: { x: 2.4, y: 0.35, z: 1.1 }, destructible: true, health: 2, materialType: "wood" },
            { position: { x: 20.1, y: 0, z: 0.6 }, size: { x: 0.7, y: 4.2, z: 1.5 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 21.7, y: 0, z: 0.6 }, size: { x: 0.7, y: 4.2, z: 1.5 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 20.9, y: 4.2, z: 0.6 }, size: { x: 2.6, y: 0.4, z: 1.5 }, destructible: true, health: 3, materialType: "wood" },
            { position: { x: 23.7, y: 0, z: -0.9 }, size: { x: 0.7, y: 4.1, z: 1.4 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 25.3, y: 0, z: -0.9 }, size: { x: 0.7, y: 4.1, z: 1.4 }, destructible: true, health: 3, materialType: "stone" },
            { position: { x: 24.5, y: 4.1, z: -0.9 }, size: { x: 2.6, y: 0.4, z: 1.4 }, destructible: true, health: 3, materialType: "wood" },
            { position: { x: 27.4, y: 0, z: -2.5 }, size: { x: 0.75, y: 5.0, z: 1.6 }, destructible: true, health: 4, materialType: "stone" },
            { position: { x: 29.0, y: 0, z: -2.5 }, size: { x: 0.75, y: 5.0, z: 1.6 }, destructible: true, health: 4, materialType: "stone" },
            { position: { x: 28.2, y: 5.0, z: -2.5 }, size: { x: 2.8, y: 0.45, z: 1.6 }, destructible: true, health: 4, materialType: "wood" },
        ],
    },
];