import { LevelDef } from "./LevelData";

export const LEVELS: LevelDef[] = [
    {
        id: "level_1",
        name: "First Flight",
        skybox: "tropical",
        launcherPosition: { x: -12, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.4, z: 0 },
        maxShots: 3,
        starThresholds: [100, 200, 350],
        timeBonusThreshold: 30,
        targets: [
            { position: { x: 10, y: 0.5, z: 0 }, size: 0.9, health: 1, scoreValue: 100 },
            { position: { x: 12, y: 0.6, z: 0.3 }, size: 1, health: 1, scoreValue: 75, type: "barrel" },
            { position: { x: 14, y: 0.5, z: 1 }, size: 0.9, health: 1, scoreValue: 100 },
        ],
        obstacles: [
            {
                position: { x: 8, y: 0, z: 0 },
                size: { x: 0.5, y: 2.5, z: 2 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_2",
        name: "Little Fortress",
        skybox: "tropical",
        launcherPosition: { x: -14, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.45, z: 0 },
        maxShots: 4,
        starThresholds: [150, 350, 600],
        timeBonusThreshold: 40,
        targets: [
            { position: { x: 10, y: 0.5, z: 0 }, size: 0.8, health: 1, scoreValue: 100 },
            { position: { x: 12, y: 2.5, z: 0 }, size: 0.8, health: 1, scoreValue: 150 },
            { position: { x: 14, y: 0.5, z: -2 }, size: 0.8, health: 2, scoreValue: 200 },
        ],
        obstacles: [
            {
                position: { x: 9, y: 0, z: 0 },
                size: { x: 0.5, y: 3, z: 3 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 11, y: 2, z: 0 },
                size: { x: 3, y: 0.4, z: 2 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
            {
                position: { x: 13, y: 0, z: 0 },
                size: { x: 0.5, y: 3, z: 2 },
                destructible: true,
                health: 2,
                materialType: "stone",
            },
            {
                position: { x: 13.5, y: 0, z: -2 },
                size: { x: 1, y: 2, z: 0.5 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
        ],
    },
    {
        id: "level_3",
        name: "Scattered Pigs",
        skybox: "night",
        launcherPosition: { x: -14, y: 1, z: 0 },
        launchDirection: { x: 1, y: 0.5, z: 0 },
        maxShots: 5,
        starThresholds: [200, 450, 800],
        timeBonusThreshold: 50,
        targets: [
            { position: { x: 8, y: 0.5, z: 4 }, size: 0.8, health: 1, scoreValue: 100 },
            { position: { x: 12, y: 0.5, z: -3 }, size: 0.8, health: 1, scoreValue: 100 },
            { position: { x: 16, y: 0.5, z: 1 }, size: 0.8, health: 1, scoreValue: 150 },
            { position: { x: 20, y: 0.6, z: 0 }, size: 1, health: 1, scoreValue: 75, type: "barrel" },
            { position: { x: 20, y: 3, z: 0 }, size: 1, health: 2, scoreValue: 250 },
        ],
        obstacles: [
            {
                position: { x: 7, y: 0, z: 4 },
                size: { x: 2, y: 1.5, z: 0.5 },
                destructible: true,
                health: 1,
                materialType: "wood",
            },
            {
                position: { x: 19, y: 0, z: 0 },
                size: { x: 0.5, y: 4, z: 2 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 21, y: 0, z: 0 },
                size: { x: 0.5, y: 4, z: 2 },
                destructible: true,
                health: 3,
                materialType: "stone",
            },
            {
                position: { x: 20, y: 4, z: 0 },
                size: { x: 3, y: 0.4, z: 2.5 },
                destructible: true,
                health: 2,
                materialType: "wood",
            },
        ],
    },
];